site_name: Specify-DotNet
theme: readthedocs
markdown_extensions: [fenced_code]
pages:
- Home: index.md
- Features:
  - Overview: features-overview.md
- Using Specify:
  - Getting Started: using-specify-getting-started.md
  - Configuration: using-specify-configuration.md
  - Scenario Lifecycle: using-specify-scenario-lifecycle.md
  - Supported Test Frameworks: using-specify-supported-test-frameworks.md
- Concepts:
  - SUT (System Under Test): concepts-system-under-test.md
  - Context Specification: concepts-context-specification.md